import { createPplxClient } from "../src/index";

async function main() {
  const client = createPplxClient();
  for await (const entry of client.search("quantum computing", {
    debug: true,
    // Explicitly opt into output. The SDK is silent by default.
    // The sink receives only URLs derived from server debug metadata.
    debugLogger: { debug: (message, links) => console.debug(message, links) },
  })) {
    if (entry.debug_data) {
      // Available only when the real server response includes this metadata.
      // No trace IDs or request timestamps are generated by the SDK.
    }
    if (entry.final) break;
  }
}

main().catch(console.error);
